# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  NIXNAME:
    sh: echo "${NIXNAME:-$(hostname)}"

tasks:
  switch:
    desc: Run nix to configure the local system
    aliases: [run]
    cmds:
      - task: switch-darwin
      - task: switch-nixos
    status:
      - "false"

  switch-darwin:
    internal: true
    platforms: [darwin]
    cmds:
      - nix build --extra-experimental-features nix-command --extra-experimental-features flakes ".#darwinConfigurations.{{.NIXNAME}}.system"
      - sudo ./result/sw/bin/darwin-rebuild switch --flake "$(pwd)#{{.NIXNAME}}"

  switch-nixos:
    internal: true
    platforms: [linux]
    cmds:
      - sudo NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nixos-rebuild switch --flake ".#{{.NIXNAME}}"

  test:
    desc: Build and test nix
    cmds:
      - task: test-darwin
      - task: test-nixos
    status:
      - "false"

  test-darwin:
    internal: true
    platforms: [darwin]
    cmds:
      - nix build --extra-experimental-features nix-command --extra-experimental-features flakes ".#darwinConfigurations.{{.NIXNAME}}.system"
      - sudo ./result/sw/bin/darwin-rebuild check --flake "$(pwd)#{{.NIXNAME}}"

  test-nixos:
    internal: true
    platforms: [linux]
    cmds:
      - sudo NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nixos-rebuild test --flake ".#{{.NIXNAME}}"

  install:
    desc: Initial install of nix
    cmds:
      - task: install-darwin
      - task: install-other

  install-darwin:
    desc: Install determinate Nix on macOS using native pkg
    internal: true
    platforms: [darwin]
    cmds:
      - curl -L https://install.determinate.systems/determinate-pkg/stable/Universal -o /tmp/determinate-nix.pkg
      - sudo installer -pkg /tmp/determinate-nix.pkg -tgt /

  install-other:
    desc: Install nix on Linux and Windows
    internal: true
    platforms: [linux, windows]
    cmds:
      - curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

  update:
    desc: Update external flakes
    cmds:
      - nix flake update
      - git add flake.lock
      - 'git commit -S -m "chore(nix): Update deps"'

  clean:
    desc: Cleanup nix garbage
    cmds:
      - nix-store --optimise
      - sudo nix-collect-garbage -d

  wsl:
    desc: Build a WSL installer for Windows
    internal: true
    cmds:
      - nix build ".#nixosConfigurations.wsl.config.system.build.installer"
